steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/lukelynch-io/docker-repo/electric-parrot-api:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t', 'us-central1-docker.pkg.dev/lukelynch-io/docker-repo/electric-parrot-api:$SHORT_SHA']